services:
  odoo:
    image: odoo:18
    container_name: odoo
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "8069:8069"
    networks:
      - odoo-network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network

volumes:
  odoo-data:
  db-data:

networks:
  odoo-network:
    driver: bridge